USE [master]
GO

/****** Object:  Database [BulutOto]    Script Date: 17.01.2022 23:13:38 ******/
CREATE DATABASE [BulutOto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BulutOto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BulutOto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BulutOto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BulutOto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BulutOto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BulutOto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BulutOto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BulutOto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BulutOto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BulutOto] SET ARITHABORT OFF 
GO

ALTER DATABASE [BulutOto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BulutOto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BulutOto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BulutOto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BulutOto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BulutOto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BulutOto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BulutOto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BulutOto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BulutOto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BulutOto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BulutOto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BulutOto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BulutOto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BulutOto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BulutOto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BulutOto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BulutOto] SET RECOVERY FULL 
GO

ALTER DATABASE [BulutOto] SET  MULTI_USER 
GO

ALTER DATABASE [BulutOto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BulutOto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BulutOto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BulutOto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BulutOto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BulutOto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BulutOto] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BulutOto] SET  READ_WRITE 
GO

